name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: yarn --frozen-lockfile

    - name: Build
      run: yarn build

    - name: Build examples
      run: yarn build-examples

    - name: Test
      run: yarn test
