name: Build

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '15.x'

    - name: Install dependencies
      run: yarn install --frozen-lockfile

    - name: Build ray-tracer
      run: yarn build-src

    - name: Build test
      run: yarn build-test

    - name: Test
      run: yarn test

    - name: Build examples
      run: yarn build-examples

    - name: Build worker
      run: yarn build-worker

    - name: Build docs
      run: yarn build-docs
